### ISSUE TITLE
NPM Error: No compatible version found: blitline

### ISSUE THREAD

**Issue by zerojuan** [blitline-dev/blitline_node#1]
I'm getting this error when I use npm to install blitline:       

```
   npm ERR! Error: No compatible version found: blitline
   npm ERR! No valid targets found.
   npm ERR! Perhaps not compatible with your version of node?
   npm ERR!     at installTargetsError (/tmp/node-npm-UStX/lib/cache.js:424:10)
   npm ERR!     at /tmp/node-npm-UStX/lib/cache.js:406:17
   npm ERR!     at saved (/tmp/node-npm-UStX/lib/utils/npm-registry-client/get.js:136:7)
   npm ERR!     at cb (/tmp/node-npm-UStX/node_modules/graceful-fs/graceful-fs.js:36:9)
   npm ERR! Report this *entire* log at:
   npm ERR!     <http://github.com/isaacs/npm/issues>
   npm ERR! or email it to:
   npm ERR!     <npm-@googlegroups.com>
   npm ERR!
   npm ERR! System Linux 2.6.32-343-ec2
   npm ERR! command "/tmp/node-node-hmaq/bin/node" "/tmp/node-npm-UStX/cli.js" "install" "--production"
   npm ERR! cwd /tmp/build_21ikurogvfndo
   npm ERR! node -v v0.4.7
   npm ERR! npm -v 1.0.106
   npm ERR!
   npm ERR! Additional logging details can be found in:
   npm ERR!     /tmp/build_21ikurogvfndo/npm-debug.log
   npm not ok
```

**Comment by blitline-dev** [comment]
This should be fixed with latest update.

**Comment by zerojuan** [comment]
thanks
